export enum Event {
  UPDATE_WORDS = 'UPDATE_WORDS',
  RENDER_WORDS = 'RENDER_WORDS',
  ALERT = 'ALERT'
}

export enum EventSource {
  CONTENT_SCRIPT = 'CONTENT_SCRIPT',
  BACKGROUND = 'BACKGROUND',
  POPUP = 'POPUP'
}
